# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_weather(object):
    def setupUi(self, weather):
        weather.setObjectName("weather")
        weather.resize(507, 492)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(18)
        weather.setFont(font)
        self.select_city_label = QtWidgets.QLabel(weather)
        self.select_city_label.setGeometry(QtCore.QRect(80, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.select_city_label.setFont(font)
        self.select_city_label.setObjectName("select_city_label")
        self.comboBox_select_city = QtWidgets.QComboBox(weather)
        self.comboBox_select_city.setGeometry(QtCore.QRect(210, 40, 150, 31))
        self.comboBox_select_city.setObjectName("comboBox_select_city")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.pushButton_query = QtWidgets.QPushButton(weather)
        self.pushButton_query.setGeometry(QtCore.QRect(90, 420, 91, 41))
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_clear = QtWidgets.QPushButton(weather)
        self.pushButton_clear.setGeometry(QtCore.QRect(280, 420, 81, 41))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.textEdit_result = QtWidgets.QTextEdit(weather)
        self.textEdit_result.setGeometry(QtCore.QRect(40, 90, 431, 301))
        self.textEdit_result.setAutoFillBackground(False)
        self.textEdit_result.setObjectName("textEdit_result")

        self.retranslateUi(weather)
        self.pushButton_query.clicked.connect(weather.queryWeather)
        self.pushButton_clear.clicked.connect(weather.accept)
        QtCore.QMetaObject.connectSlotsByName(weather)

    def retranslateUi(self, weather):
        _translate = QtCore.QCoreApplication.translate
        weather.setWindowTitle(_translate("weather", "城市天气查询"))
        self.select_city_label.setText(_translate("weather", "选择城市"))
        self.comboBox_select_city.setItemText(0, _translate("weather", "北京"))
        self.comboBox_select_city.setItemText(1, _translate("weather", "上海"))
        self.comboBox_select_city.setItemText(2, _translate("weather", "南京"))
        self.comboBox_select_city.setItemText(3, _translate("weather", "天津"))
        self.comboBox_select_city.setItemText(4, _translate("weather", "广州"))
        self.comboBox_select_city.setItemText(5, _translate("weather", "深圳"))
        self.comboBox_select_city.setItemText(6, _translate("weather", "乌鲁木齐"))
        self.comboBox_select_city.setItemText(7, _translate("weather", "齐齐哈尔"))
        self.comboBox_select_city.setItemText(8, _translate("weather", "南宁"))
        self.comboBox_select_city.setItemText(9, _translate("weather", "桂林"))
        self.comboBox_select_city.setItemText(10, _translate("weather", "徐州"))
        self.pushButton_query.setText(_translate("weather", "查询"))
        self.pushButton_clear.setText(_translate("weather", "清空"))
