# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather-textBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_weather(object):
    def setupUi(self, weather):
        weather.setObjectName("weather")
        weather.resize(511, 494)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        weather.setFont(font)
        self.select_city_label = QtWidgets.QLabel(weather)
        self.select_city_label.setGeometry(QtCore.QRect(260, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.select_city_label.setFont(font)
        self.select_city_label.setObjectName("select_city_label")
        self.comboBox_select_city = QtWidgets.QComboBox(weather)
        self.comboBox_select_city.setGeometry(QtCore.QRect(320, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(60)
        self.comboBox_select_city.setFont(font)
        self.comboBox_select_city.setObjectName("comboBox_select_city")
        self.comboBox_select_city.addItem("")
        self.comboBox_select_city.addItem("")
        self.pushButton_query = QtWidgets.QPushButton(weather)
        self.pushButton_query.setGeometry(QtCore.QRect(90, 420, 91, 41))
        self.pushButton_query.setObjectName("pushButton_query")
        self.pushButton_clear = QtWidgets.QPushButton(weather)
        self.pushButton_clear.setGeometry(QtCore.QRect(280, 420, 81, 41))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_province = QtWidgets.QLabel(weather)
        self.label_province.setGeometry(QtCore.QRect(40, 42, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_province.setFont(font)
        self.label_province.setObjectName("label_province")
        self.comboBox_province = QtWidgets.QComboBox(weather)
        self.comboBox_province.setGeometry(QtCore.QRect(110, 40, 121, 31))
        self.comboBox_province.setObjectName("comboBox_province")
        self.textBrowser_result = QtWidgets.QTextBrowser(weather)
        self.textBrowser_result.setGeometry(QtCore.QRect(40, 90, 421, 311))
        self.textBrowser_result.setObjectName("textBrowser_result")

        self.retranslateUi(weather)
        self.pushButton_query.clicked.connect(weather.queryWeather)
        self.pushButton_clear.clicked.connect(weather.clearText)
        self.comboBox_province.currentIndexChanged['int'].connect(weather.onchange_city_comboBox)
        QtCore.QMetaObject.connectSlotsByName(weather)

    def retranslateUi(self, weather):
        _translate = QtCore.QCoreApplication.translate
        weather.setWindowTitle(_translate("weather", "城市天气查询"))
        self.select_city_label.setText(_translate("weather", "城市:"))
        self.comboBox_select_city.setItemText(0, _translate("weather", "北京"))
        self.comboBox_select_city.setItemText(1, _translate("weather", "上海"))
        self.pushButton_query.setText(_translate("weather", "查询"))
        self.pushButton_clear.setText(_translate("weather", "清空"))
        self.label_province.setText(_translate("weather", "省份："))
